// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tbl_Slide_GioiThieuTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tbl_Slide_GioiThieuTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "201703221537452_tbl_Slide_GioiThieu.Title"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
